<?php
class google_analytics{
	public function google_analytics(){
		
		$desc = 'Google Analytics is a tool to track users that visit your site.';
		
		if(strpos(PAGE, 'google-analytics.com/ga.js') === false){
			theme::addToBlock('seo', theme::lineItem('x', 'Google Analytics Installed', 'no', $desc));
			score::add(50, 2, 'wb', 'google_analytics');
			score::add(50, 2, 'dm', 'google_analytics');
		}else{
			theme::addToBlock('seo', theme::lineItem('check', 'Google Analytics Installed', 'yes', $desc));
			score::add(100, 2, 'wb', 'google_analytics');
			score::add(100, 2, 'dm', 'google_analytics');
		}
	}
}
?>