<?php

class conversion_form{
	public function conversion_form(){
		$forms = count(pq(':submit:not([value*=search]))'));
				
		$bTitle = 'User Conversion';
		$bDesc = 'This section shows whether or not yoru business is actively trying to convert and track your customers through he sales process of your website.';
		
		theme::createBlock('cro', $bTitle, $bDesc);
		if($forms > 0){
			theme::addToBlock('cro', theme::lineItem('check', 'Conversion Form Detected', 'yes'));
			score::add(100, 4);
		}else{
			theme::addToBlock('cro', theme::lineItem('x', 'Conversion Form Detected', 'no'));
			score::add(50, 4);
		}
	}
}


?>