<?php
class iframe{
	public function iframe(){
		$iframe = array();
		foreach(pq('iframe') as $frame){
			array_push($iframe, $frame);
		}
		
		$count = count($iframe);
		
		$bTitle = 'hosting + development';
		$bDesc = 'This section looks at the actual code of the website, what it is built with, and if you have any coding and compliance issues.';	
		
		theme::createBlock('code', $bTitle, $bDesc);
		
		$desc = 'iFrame technology has mostly fallen out of favor, however there are some use cases where it can still be used';
		
		if($count > 0){
			theme::addToBlock('code', theme::lineItem('x', 'iFrames Detected', 'yes', $desc));
			score::add(45, 1, 'wb', 'iframe'); 
			score::add(45, 1, 'dm', 'iframe'); 
		}else{
			theme::addToBlock('code', theme::lineItem('check', 'iFrames Detected', 'no', $desc));
			score::add(100, 1, 'wb', 'iframe');
			score::add(100, 1, 'dm', 'iframe'); 
		}
	}
}
?>