<?php
class flash{
	public function flash(){
		$items = array();
		foreach(pq('object') as $obj){
			array_push($items, $obj);
		}
	
		$objs = count($items);
		
		$bTitle = 'hosting + development';
		$bDesc = 'This section looks at the actual code of the website, what it is built with, and if you have any coding and compliance issues.';	
		
		theme::createBlock('code', $bTitle, $bDesc);
		
		$desc = 'Adobe flash content cannot be viewed on most mobile devices, and is recommended only under very specific use cases.';
		
		if($objs > 0){
			theme::addToBlock('code', theme::lineItem('x', 'Adobe Flash Detected', 'yes', $desc));
			score::add(50, 3, 'wb', 'flash');
			score::add(50, 3, 'dm', 'flash'); 
		}else if(strpos(PAGE, 'swfObject')){ // SWF Object
			theme::addToBlock('code', theme::lineItem('x', 'Adobe Flash Detected', 'yes', $desc));
			score::add(75, 3, 'wb', 'flash'); 
			score::add(75, 3, 'dm', 'flash'); 
		}else{
			theme::addToBlock('code', theme::lineItem('check', 'Adobe Flash Detected', 'no', $desc));
			score::add(100, 3, 'wb', 'flash'); 
			score::add(100, 3, 'dm', 'flash'); 
		}
	}
}
?>